version: '2'
services:
    jhipstertuto-app:
        image: jhipstertuto
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertuto-postgresql:5432/jhipsterTuto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertuto-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstertuto-postgresql
