version: '2'
services:
    jhipstertuto-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterTuto/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterTuto
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
